CREATE TABLE IF NOT EXISTS USER_CONNECTIONS (
    UID VARCHAR NOT NULL DEFAULT uuid_generate_v4(),
    user_uid VARCHAR NOT NULL,
    platform VARCHAR(50) NOT NULL,
    profile_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_uid) REFERENCES users(uid),
    CONSTRAINT PK_USER_CONNECTIONS PRIMARY KEY (UID)
)
