CREATE TABLE IF NOT EXISTS user_info(
    UID VARCHAR(100)  NOT NULL DEFAULT public.uuid_generate_v4(),
    USER_UID VARCHAR(100),
    PROFILE_PICTURE TEXT,
    INFO TEXT,
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_INFO PRIMARY KEY (UID),
    FOREIGN KEY (USER_UID) REFERENCES USERS(UID)
    );
