CREATE TABLE IF NOT EXISTS users(
    UID VARCHAR(100)  NOT NULL DEFAULT public.uuid_generate_v4(),
    AUTH_UID VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100),
    STATUS VARCHAR(20) DEFAULT 'INACTIVE',
    AUTH_PROVIDER VARCHAR(20) DEFAULT 'NORMAL',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER PRIMARY KEY (UID)
);
